### ISSUE TITLE
The db does not seem to be populated at launch

### ISSUE THREAD

**Issue by cadesalaberry** [Synerzip/loopback-connector-sqlite#17]
Here is my **datasources.js**:
```js
{
  "db__old": {
    "name": "db",
    "connector": "memory"
  },
  "db": {
    "name"     : "storage",
    "connector": "sqlite",
    "debug"    : false,
    "file_name": "./test.sqlite3"
  }
}
```

When launching my loopback server, it does not seem like there is any migration happening. Here is the error I am getting:

```
{ [Error: SQLITE_ERROR: no such table: ACL] errno: 1, code: 'SQLITE_ERROR' }
Unhandled error for request POST /Members: Error: SQLITE_ERROR: no such table: ACL
    at Error (native)
```

Is there any steps to follow to get this working ?

**Comment by johnsoftek** [comment]
@cadesalaberry Migration is not invoked automatically by Loopback. See https://loopback.io/doc/en/lb2/Creating-a-database-schema-from-models.html for background. You will need to decide when to trigger a migration.

**Comment by cadesalaberry** [comment]
Thanks,

I am using this connector to run my tests. My problem came from the fact that I was using postgres specific functions in my migration. It was crashing silently.
