### ISSUE TITLE
Absolute paths for database

### ISSUE THREAD

**Issue by marcominetti** [Synerzip/loopback-connector-sqlite#4]
Hi, I'm having some problems using it when passing absolute path instead of relative...

The line at https://github.com/Synerzip/loopback-connector-sqlite/blob/master/lib/sqlite3db.js#L59

```
var file_name = ((self.file_name != null) ? ("./" + self.file_name) : ":memory:");
```

Could be better to prepend "./" only when the self.file_name does not start with require('path').sep? Or requiring developer to insert it?

Sounds reasonable to you?

I can pull request...

**Comment by tushar-chauhan** [comment]
@marcominetti Your suggestion seems good. I guess I will remove the `"./"` from that statement and update the readme for the support of absolute path and those who want to use project's directory to keep/generate the SQLite file then they will need to add `"./"` to the file_name itself.
I think putting in conditions to check for the presence of path separator is not that necessary as absolute paths in OS like windows doesn't start with a (`/`) separator

**Comment by marcominetti** [comment]
Great! Thanks!
