### ISSUE TITLE
"Set" and "Transaction" could not be used as model name

### ISSUE THREAD

**Issue by kidwm** [Synerzip/loopback-connector-sqlite#5]
I switched from mongodb to sqlite3 in my loopback project, and find that it does not work and give such error:
```
Error: SQLITE_ERROR: near "Set": syntax error
    at Error (native)
```
and it worked after remove these models in my model-config.json:
```
  "Transaction": {
    "dataSource": "sqlite3",
    "public": true
  },
  "Set": {
    "dataSource": "sqlite3",
    "public": true
  }
```

**Comment by tushar-chauhan** [comment]
@kidwm `Transaction` & `Set` are amongst the keywords in SQLite3. Checkout [all SQLite3 keywords here](https://sqlite.org/lang_keywords.html). It says there that _these **keywords** may **not be used** as the **names of tables, indices, columns, databases, user-defined functions, collations, virtual table modules, or any other named object**._ I would like to suggest you to use some different Model names than those keywords. I hope this information helps you.

**Comment by kidwm** [comment]
@tushar-chauhan Thank you for answering. Will you add the info to README.md then close this issue?

**Comment by tushar-chauhan** [comment]
@kidwm Done. Thanks for pointing this out.
