### ISSUE TITLE
what does this mean ? var db = new DataSource(require('../index'), {

### ISSUE THREAD

**Issue by ramstein74** [Synerzip/loopback-connector-sqlite#6]
i dont understand what is this in the example

var db = new DataSource(require('../index'), {

i get the error cannot find module ../index

what is the module index ?

**Comment by johnsoftek** [comment]
cd to the examples directory. index.js is in the directory above

**Comment by tushar-chauhan** [comment]
@ramstein74 If you are in connector's root directory you need to run the examples using relative path, e.g., `node examples/[example_file_name]`.
If you are in **examples** directory then you need to run the example files directly using 
`node [example_file_name]`.
The **index.js** exposes the connector module for creating the Datasource object.
Let me know if you are not able to run the examples. 
Also, close this issue if they are running successfully.
