### ISSUE TITLE
SQLiteDB.prototype.toDatabase changes object contents when val is an array

### ISSUE THREAD

**Issue by jouke** [Synerzip/loopback-connector-sqlite#9]
Hello,

When using loopback-connector-sqlite in a change-tracked setup I came across some server crashes, that after long debugging came down to an issue in this connector.

Loopback's PersistedModel.diff does a query like this:

```
   this.find({
      where: {
        modelName: modelName,
        modelId: {inq: modelIds}
      }
    }, function(err, allLocalChanges) {
```

Later in the code, the modelIds are re-used to match a list of changes. However, this match can never be made, because `toDatabase()` modifies the `val` parameter when escaping the values.

The fix is simple: create a new datastructure with the escaped values and leave the val parameter untouched.

I've created a pull request for this: https://github.com/Synerzip/loopback-connector-sqlite/pull/8

**Comment by jouke** [comment]
oh, and the pull request includes a test to prove the behaviour. You can run the tests on the current code and it will fail, run it after pulling my code, and it will succeed.

**Comment by tushar-chauhan** [comment]
@jouke closing this as the pull request #8 is already merged now.
